### ISSUE TITLE
Exception starting filter [CustomFilter]

### ISSUE THREAD

**Issue by buderre** [codecentric/chaos-monkey-spring-boot#149]
## Expected Behavior
Application should start

## Current Behavior
Application does not start. Instead the application fails to start and results in the exception
`
java.lang.NullPointerException: null
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:106)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4530)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5169)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
`

The affected line of code is in the class org.springframework.web.filter.GenericFilterBean. The application can not initialize the logger variable and therefore results in a NullPointerException.

## Possible Solution
Unknown to me

## Steps to Reproduce
Not needed. Just start the application.

## Context (Environment)
* Spring Boot 2.1.7
* JDK Amazon Corretto 11.04
* A custom filter that extends the org.springframework.web.filter.GenericFilterBean

**Comment by maiksensi** [comment]
Hey @buderre, 
thanks for submitting a bug report. That seems strange! Any chance you can tell us what application you used? Did you use  one of our example applications in the project or something you setup?

**Comment by medmes** [comment]
Hey @buderre. could you please tell us, more details about the issue?

**Comment by buderre** [comment]
Hey guys. I will try to reproduce the behavior with a small code example and reach out to you guys. Sorry for the delay.

**Comment by maiksensi** [comment]
Hey @buderre,
did you have some time to create a small example? If you fixed  the issue, please let us know what you did do. We are curious! I will close this issue in about weeks, but feel free to re-open it whenever you're ready.

**Comment by Zerotul** [comment]
Hey guys. I suffer from this too. I reproduced the behavior in a simple project https://github.com/Zerotul/chaos-monkey-starting-filter

**Comment by maiksensi** [comment]
@Zerotul thanks for the example 🙇 . I'll have a look at it.

**Comment by maiksensi** [comment]
Hmm I had a fast look at it this morning. But to be honest, I need more digging into this because so far I don't have a clue on how to solve this :(. Any suggestions?

**Comment by juanpablo-santos** [comment]
Hi @maiksensi, 

came across with https://github.com/spring-projects/spring-boot/issues/8605 recently, which seems to be the same issue and suggests some workarounds. 

HTH

**Comment by dkdew** [comment]
hi,

i was facing this issue with custom-filters in my spring-boot app. The application fails to run with chaos-monkey profile active, when we have declared the CustomFilter with @component annotation. 
The simple workaround is to create the filter with @Bean annotations.

[Here ](https://github.com/dkdew/spring-boot-chaos-monkey-starting-filter) is the example code, how i did it.
https://github.com/dkdew/spring-boot-chaos-monkey-starting-filter
