### ISSUE TITLE
Latency Assault on the service layer which calls legacy SOAP/Rest Clients

### ISSUE THREAD

**Issue by abecedarius** [codecentric/chaos-monkey-spring-boot#57]
I have the boot app with the chaos monkey enabled. I have induced the latency by using the properties

` chaos.monkey.assaults.latencyRangeStart=3000
 chaos.monkey.assaults.latencyRangeEnd=15000
chaos.monkey.assaults.latencyActive=true `

Now, this is inducing the latency on the controller layer, But I have called various legacy endpoints(SOAP and Rest) in the service layer. Theseproperties are not inducing any latency on these backend clients.
Is there any other property that can induce the latency on the Soap/rest clients?

**Comment by MrBW** [comment]
The Chaos Monkey will only slow down your response and not the components you use yourself. 

But if you make these remote calls in a component using an @Service or @Component annotated class and not directly as a private method in your class, you can slow it down using the Chaos Monkey.

**Comment by abecedarius** [comment]
Thanks, 
I am able to do the latency assault on the @service or @controller or @repository classes but it is not able to do the latency assault on the @component classes.

Getting below exception and the application is shutting down soon after that.

```

20-12-2018 14:43:13.937 main [pre-cache-app] [MessageId-] ERROR org.springframework.boot.SpringAppli
cation:842 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappi
ngHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet
/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Initialization of bean failed; nested exc
eption is java.lang.IllegalArgumentException: bound must be greater than origin
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean
(AbstractAutowireCapableBeanFactory.java:587) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(A
bstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(Abstract
BeanFactory.java:317) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(Defau
ltSingletonBeanRegistry.java:228) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFacto
ry.java:315) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory
.java:199) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingle
tons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitializ
ation(AbstractApplicationContext.java:869) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicatio
nContext.java:550) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(S
ervletWebServerApplicationContext.java:140) ~[spring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-bo
ot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [sp
ring-boot-2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2
.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-
2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-
2.0.2.RELEASE.jar!/:2.0.2.RELEASE]
        at com.bt.mcso.precacheapp.PreCacheAppApplication.main(PreCacheAppApplication.java:34) [clas
ses!/:0.0.2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [pre-cache
-app-0.0.2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [pre-cache-app-0.0.2-SN
APSHOT.jar:0.0.2-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [pre-cache-app-0.0.2-SN
APSHOT.jar:0.0.2-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [pre-cache-app-0.0.
2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: bound must be greater than origin
        at java.util.concurrent.ThreadLocalRandom.nextInt(Unknown Source) ~[?:1.8.0_121]
        at de.codecentric.spring.boot.chaos.monkey.assaults.LatencyAssault.attack(LatencyAssault.jav
a:53) ~[chaos-monkey-spring-boot-2.0.1.jar!/:?]
        at de.codecentric.spring.boot.chaos.monkey.component.ChaosMonkey.chooseAndRunAttack(ChaosMon
key.java:70) ~[chaos-monkey-spring-boot-2.0.1.jar!/:?]
        at de.codecentric.spring.boot.chaos.monkey.component.ChaosMonkey.callChaosMonkey(ChaosMonkey
.java:57) ~[chaos-monkey-spring-boot-2.0.1.jar!/:?]
        at de.codecentric.spring.boot.chaos.monkey.watcher.SpringComponentAspect.intercept(SpringCom
ponentAspect.java:55) ~[chaos-monkey-spring-boot-2.0.1.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(Abs
tractAspectJAdvice.java:644) ~[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJA
dvice.java:633) ~[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~
[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo
cation.java:185) ~[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationIn
terceptor.java:92) ~[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvo
cation.java:185) ~[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(Cglib
AopProxy.java:688) ~[spring-aop-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at springfox.documentation.schema.property.ObjectMapperBeanPropertyNamingStrategy$$EnhancerB
ySpringCGLIB$$ea6f2ebd.onApplicationEvent(<generated>) ~[springfox-schema-2.7.0.jar!/:2.7.0]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(Simp
leApplicationEventMulticaster.java:172) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(Simple
ApplicationEventMulticaster.java:165) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(Simple
ApplicationEventMulticaster.java:139) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractAppli
cationContext.java:400) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractAppli
cationContext.java:354) ~[spring-context-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at springfox.documentation.spring.web.ObjectMapperConfigurer.fireObjectMapperConfiguredEvent
(ObjectMapperConfigurer.java:90) ~[springfox-spring-web-2.7.0.jar!/:2.7.0]
        at springfox.documentation.spring.web.ObjectMapperConfigurer.configureMessageConverters(Obje
ctMapperConfigurer.java:66) ~[springfox-spring-web-2.7.0.jar!/:2.7.0]
        at springfox.documentation.spring.web.ObjectMapperConfigurer.postProcessBeforeInitialization
(ObjectMapperConfigurer.java:47) ~[springfox-spring-web-2.7.0.jar!/:2.7.0]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPos
tProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.0.6.RE
LEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBe
an(AbstractAutowireCapableBeanFactory.java:1698) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean
(AbstractAutowireCapableBeanFactory.java:579) ~[spring-beans-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
        ... 23 more
BPTM: Thu Dec 20 14:43:14 IST 2018: INFO: Logging shutdown thread started
BPTM: Thu Dec 20 14:43:14 IST 2018: INFO: Logging shutdown thread finished

```

**Comment by MrBW** [comment]
@Componet is currently not working correctly, will take a close look on it

**Comment by maiksensi** [comment]
This should be fixed with https://github.com/codecentric/chaos-monkey-spring-boot/commit/5e34d37422929713ee70a171563405d53c0621a5

**Comment by maiksensi** [comment]
Closing this for now. Feel free to open this again if this is not fixed with the next release.
