### ISSUE TITLE
Facing issue with @Component Watcher

### ISSUE THREAD

**Issue by navdeepraheja** [codecentric/chaos-monkey-spring-boot#64]
I am using SB Chaos monkey 2.0.1 and SPring context 5.0. Getting the below error on app startup with @Component watcher = true.

org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.reactive.ReactiveWebServerFactoryConfiguration$EmbeddedNetty': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'chaos.monkey-de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyProperties': Could not bind properties to 'ChaosMonkeyProperties' : prefix=chaos.monkey, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.context.properties.ConversionServiceDeducer$Factory': Unsatisfied dependency expressed through method 'setConverters' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'componentAspect': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82) ~[spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67) ~[spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]

**Comment by vchandrakar78** [comment]
Hi, I am seeing the same error when i set the component watcher to true. 

    watcher:
      component: true
      controller: false
      repository: false
      restController: false
      service: false

**Comment by denniseffing** [comment]
I can't reproduce this. Can you send me a code sample exhibiting your issue?
